version: '3.7'

networks:
  private:
    driver: bridge


services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - private
    ports:
      - "9000"
    volumes:
      - type: bind
        source: ./htdocs
        target: /var/www/html
    cap_add:
      - SYS_PTRACE
    environment:
      - PHP_FPM_CONF_1=global:log_level:notice
      - PHP_FPM_CONF_2=global:include:/etc/php/7.4/fpm/pool.d/*.conf
      - PHP_FPM_INI_1=PHP:memory_limit:128M
      - PHP_FPM_INI_2=Date:date.timezone:UTC
      - PHP_FPM_INI_3=Session:session.use_cookies:1
      - PHP_FPM_POOL_1=www:pm.status_path:/status
      - PHP_FPM_POOL_2=www:request_slowlog_timeout:2s
      - PHP_FPM_POOL_3=www:php_admin_value[memory_limit]:128M

  apache:
    image: raasss/apache-ubuntu-21.04:latest
    networks:
      - private
    ports:
      - "80"
      - "443"
    environment:
     - PHP_FPM_SERVER=php-fpm
    volumes:
      - type: bind
        source: ./htdocs
        target: /var/www/html
        read_only: true
